
class Html {
  StringBuffer buffer = new StringBuffer();
  bool startOfLine = true;
  List<String> tags = [];
  List<bool> indents = [];
  String indent = '';

  Html() {
    writeln('<!DOCTYPE html>');
    writeln();
    writeln('<!-- generated by docs.dart -->');
    writeln();
  }

  void start({
    String title,
    String cssRef,
    String inlineCss
  }) {
    startTag('html', newLine: false);
    writeln();
    startTag('head');

    writeln('<meta charset="utf-8">');
    writeln('<meta name="viewport" content="width=device-width, initial-scale=1.0">');

    if (title != null) {
      writeln('<title>${title}</title>');
    }

    // TODO: jquery?
    writeln('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">');
    writeln('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>');
    writeln('<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700" rel="stylesheet" type="text/css">');

    if (cssRef != null) {
      writeln('<link href="${cssRef}" rel="stylesheet" media="screen">');
    }

    if (inlineCss != null) {
      startTag('style');
      writeln(inlineCss.trim());
      endTag();
    }

    // head
    endTag();

    writeln();

    startTag('body', attributes: "class=guide", newLine: false);
    writeln();
  }

  void startTag(String tag, {String attributes, bool newLine: true}) {
    if (attributes != null) {
      if (newLine) {
        writeln('<${tag} ${attributes}>');
      } else {
        write('<${tag} ${attributes}>');
      }
    } else {
      if (newLine) {
        writeln('<${tag}>');
      } else {
        write('<${tag}>');
      }
    }

    indents.add(newLine);

    if (newLine) {
      indent = '$indent\t';
    }

    tags.add(tag);
  }

  void tag(String tag, {String attributes, String contents}) {
    if (attributes != null) {
      if (contents != null) {
        writeln('<$tag $attributes>$contents</$tag>');
      } else {
        writeln('<$tag $attributes></$tag>');
      }
    } else {
      if (contents != null) {
        writeln('<$tag>$contents</$tag>');
      } else {
        writeln('<$tag></$tag>');
      }
    }
  }

  void endTag() {
    String tag = tags.removeLast();
    bool wasIndent = indents.removeLast();
    if (wasIndent) {
      indent = indent.substring(0, indent.length - 1);
    }
    writeln('</${tag}>');
  }

  void end() {
    // body
    endTag();

    // html
    endTag();
  }

  String toString() {
    return buffer.toString();
  }

  void write(String str) {
    if (startOfLine) {
      buffer.write(indent);
      startOfLine = false;
    }

    buffer.write(str);
  }

  void writeln([String str]) {
    if (str == null) {
      write('\n');
    } else {
      write('${str}\n');
    }

    startOfLine = true;
  }
}
